
SELECT		
   N_I_ANNEE,
   C_I_TYPE,
   1000.0 AS AMOUNT,
   '2024-03-10' AS PAYMENT_DATE,
   MIN(VA_TYPE) AS VA_PERIOD,
   MIN(VA_DATE) AS VA_DATE
FROM
   (
   SELECT N_I_ANNEE, C_I_TYPE, N_I_YEAR_BILAN, N_I_MONTH_BILAN, 'VA_PERIOD_1' AS VA_TYPE, D_I_DATE_VA1 AS VA_DATE FROM CALCISOC.VA_PERIOD WHERE D_I_DATE_VA1 IS NOT NULL 
   UNION
   SELECT N_I_ANNEE, C_I_TYPE, N_I_YEAR_BILAN, N_I_MONTH_BILAN, 'VA_PERIOD_2' AS VA_TYPE, D_I_DATE_VA2 AS VA_DATE FROM CALCISOC.VA_PERIOD WHERE D_I_DATE_VA2 IS NOT NULL 
   UNION
   SELECT N_I_ANNEE, C_I_TYPE, N_I_YEAR_BILAN, N_I_MONTH_BILAN, 'VA_PERIOD_3' AS VA_TYPE, D_I_DATE_VA3 AS VA_DATE FROM CALCISOC.VA_PERIOD WHERE D_I_DATE_VA3 IS NOT NULL 
   UNION
   SELECT N_I_ANNEE, C_I_TYPE, N_I_YEAR_BILAN, N_I_MONTH_BILAN, 'VA_PERIOD_4' AS VA_TYPE, D_I_DATE_VA4 AS VA_DATE FROM CALCISOC.VA_PERIOD WHERE D_I_DATE_VA4 IS NOT NULL
   ) AS T
WHERE
   N_I_ANNEE=2024
   AND C_I_TYPE='SPEC'
   AND N_I_YEAR_BILAN=2024 
   AND N_I_MONTH_BILAN=3
   AND VA_DATE >= CAST('2024-03-10' AS DATE)
GROUP BY 
   N_I_ANNEE,C_I_TYPE
HAVING
   MIN(VA_DATE) > CAST('2024-03-10' AS DATE)
