SET DATABASE UNIQUE NAME HSQLDB7F72B6630F
SET DATABASE GC 0
SET DATABASE DEFAULT RESULT MEMORY ROWS 0
SET DATABASE EVENT LOG LEVEL 0
SET DATABASE SQL REFERENCES FALSE
SET DATABASE SQL SIZE TRUE
SET DATABASE SQL NAMES FALSE
SET DATABASE TRANSACTION CONTROL LOCKS
SET DATABASE DEFAULT ISOLATION LEVEL READ COMMITTED
SET FILES WRITE DELAY 500 MILLIS
SET FILES BACKUP INCREMENT TRUE
SET FILES CACHE SIZE 10000
SET FILES CACHE ROWS 50000
SET FILES SCALE 8
SET FILES LOB SCALE 32
SET FILES DEFRAG 20
SET FILES NIO TRUE
SET FILES LOG TRUE
SET FILES LOG SIZE 50
SET DATABASE TEXT TABLE DEFAULTS ''
-- DCL
CREATE USER SA PASSWORD ''
CREATE SCHEMA PUBLIC AUTHORIZATION DBA
CREATE SCHEMA "CALCISOC" AUTHORIZATION SA

-- DDL
SET SCHEMA "CALCISOC"
--CREATE MEMORY TABLE "chinook"."InvoiceLine"("InvoiceLineId" INTEGER NOT NULL,"InvoiceId" INTEGER NOT NULL,"TrackId" INTEGER NOT NULL,"UnitPrice" DECIMAL(10,2) NOT NULL,"Quantity" INTEGER NOT NULL,CONSTRAINT "PK_InvoiceLine" PRIMARY KEY("InvoiceLineId"),CONSTRAINT "FK_InvoiceLineInvoiceId" FOREIGN KEY("InvoiceId") REFERENCES "chinook"."Invoice"("InvoiceId"))

CREATE MEMORY TABLE CALCISOC.TEST (
TYPE_TEST VARCHAR(4) NOT NULL,
DATE_BALANS SMALLINT NOT NULL,
DATE_TEST DATE
CONSTRAINT "PK_TEST" PRIMARY KEY(TYPE_TEST,DATE_BALANS)
);

--ALTER TABLE "chinook"."Album" ADD CONSTRAINT "FK_AlbumArtistId" FOREIGN KEY("ArtistId") REFERENCES "chinook"."Artist"("ArtistId")

ALTER SEQUENCE SYSTEM_LOBS.LOB_ID RESTART WITH 1
SET DATABASE DEFAULT INITIAL SCHEMA PUBLIC

GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.YES_OR_NO TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.TIME_STAMP TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.CARDINAL_NUMBER TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.CHARACTER_DATA TO PUBLIC
GRANT USAGE ON DOMAIN INFORMATION_SCHEMA.SQL_IDENTIFIER TO PUBLIC
GRANT DBA TO SA
SET SCHEMA SYSTEM_LOBS
INSERT INTO BLOCKS VALUES(0,2147483647,0)

-- DML
SET SCHEMA "CALCISOC"
--INSERT INTO "chinook"."Album" VALUES(1,'For Those About To Rock We Salute You',1)

