spring.application.name=ovcogr

# HSQLDB Configuration
spring.datasource.url=jdbc:hsqldb:file:data/bnb;shutdown=false;read-only=false;hsqldb.lock_file=false
spring.datasource.driverClassName=org.hsqldb.jdbc.JDBCDriver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.HSQLDialect
# JPA
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
# JSP
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
