spring.application.name=sandbox
# DB2
spring.datasource.url=jdbc:db2://zldbfisd2.rdc.finbel.intra:51000/MATTEST:currentSchema=MEDATTEST;
spring.datasource.username=dgucciar
spring.datasource.password=
spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver
spring.jpa.database-platform=org.hibernate.dialect.DB2Dialect
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
hikari.read-only=true
hikari.auto-commit: false
#time-out
spring.mvc.async.request-timeout=60000