package minfin.sandbox.model;
// Generated 7 avr. 2026, 16:25:34 by Hibernate Tools 7.3.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * AccountType generated by hbm2java
 */
@Entity
@Table(name="ACCOUNT_TYPE"
)
public class AccountType  implements java.io.Serializable {


     private long idf;
     private String code;
     private String name;
     private String nameFr;
     private String nameNl;
     @JsonManagedReference
     private Set<InvoiceInformation> invoiceInformations = new HashSet<InvoiceInformation>(0);

    public AccountType() {
    }

	
    public AccountType(long idf) {
        this.idf = idf;
    }
    public AccountType(long idf, String code, String name, String nameFr, String nameNl, Set<InvoiceInformation> invoiceInformations) {
       this.idf = idf;
       this.code = code;
       this.name = name;
       this.nameFr = nameFr;
       this.nameNl = nameNl;
       this.invoiceInformations = invoiceInformations;
    }
   
     @Id 

    
    @Column(name="IDF", unique=true, nullable=false)
    public long getIdf() {
        return this.idf;
    }
    
    public void setIdf(long idf) {
        this.idf = idf;
    }

    
    @Column(name="CODE", length=3)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="NAME", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="NAME_FR", length=255)
    public String getNameFr() {
        return this.nameFr;
    }
    
    public void setNameFr(String nameFr) {
        this.nameFr = nameFr;
    }

    
    @Column(name="NAME_NL", length=255)
    public String getNameNl() {
        return this.nameNl;
    }
    
    public void setNameNl(String nameNl) {
        this.nameNl = nameNl;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="accountType")
    public Set<InvoiceInformation> getInvoiceInformations() {
        return this.invoiceInformations;
    }
    
    public void setInvoiceInformations(Set<InvoiceInformation> invoiceInformations) {
        this.invoiceInformations = invoiceInformations;
    }




}


