package minfin.sandbox.model;
// Generated 7 avr. 2026, 16:25:34 by Hibernate Tools 7.3.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.util.Date;

/**
 * BookOrder generated by hbm2java
 */
@Entity
@Table(name="BOOK_ORDER"
)
public class BookOrder  implements java.io.Serializable {


     private int CIIdx;
     private PaperOrder paperOrder;
     private int CIQuantity;
     private String TIBookRefStart;
     private String TIBookRefEnd;
     private Date DIBookDelivery;
     private String orderReference;

    public BookOrder() {
    }

	
    public BookOrder(int CIIdx, PaperOrder paperOrder, int CIQuantity, String TIBookRefStart, String TIBookRefEnd) {
        this.CIIdx = CIIdx;
        this.paperOrder = paperOrder;
        this.CIQuantity = CIQuantity;
        this.TIBookRefStart = TIBookRefStart;
        this.TIBookRefEnd = TIBookRefEnd;
    }
    public BookOrder(int CIIdx, PaperOrder paperOrder, int CIQuantity, String TIBookRefStart, String TIBookRefEnd, Date DIBookDelivery, String orderReference) {
       this.CIIdx = CIIdx;
       this.paperOrder = paperOrder;
       this.CIQuantity = CIQuantity;
       this.TIBookRefStart = TIBookRefStart;
       this.TIBookRefEnd = TIBookRefEnd;
       this.DIBookDelivery = DIBookDelivery;
       this.orderReference = orderReference;
    }
   
     @Id 

    
    @Column(name="C_I_IDX", unique=true, nullable=false)
    public int getCIIdx() {
        return this.CIIdx;
    }
    
    public void setCIIdx(int CIIdx) {
        this.CIIdx = CIIdx;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_I_PAPER_ORDER_IDX", nullable=false)
    public PaperOrder getPaperOrder() {
        return this.paperOrder;
    }
    
    public void setPaperOrder(PaperOrder paperOrder) {
        this.paperOrder = paperOrder;
    }

    
    @Column(name="C_I_QUANTITY", nullable=false)
    public int getCIQuantity() {
        return this.CIQuantity;
    }
    
    public void setCIQuantity(int CIQuantity) {
        this.CIQuantity = CIQuantity;
    }

    
    @Column(name="T_I_BOOK_REF_START", nullable=false, length=10)
    public String getTIBookRefStart() {
        return this.TIBookRefStart;
    }
    
    public void setTIBookRefStart(String TIBookRefStart) {
        this.TIBookRefStart = TIBookRefStart;
    }

    
    @Column(name="T_I_BOOK_REF_END", nullable=false, length=10)
    public String getTIBookRefEnd() {
        return this.TIBookRefEnd;
    }
    
    public void setTIBookRefEnd(String TIBookRefEnd) {
        this.TIBookRefEnd = TIBookRefEnd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="D_I_BOOK_DELIVERY", length=10)
    public Date getDIBookDelivery() {
        return this.DIBookDelivery;
    }
    
    public void setDIBookDelivery(Date DIBookDelivery) {
        this.DIBookDelivery = DIBookDelivery;
    }

    
    @Column(name="ORDER_REFERENCE", length=20)
    public String getOrderReference() {
        return this.orderReference;
    }
    
    public void setOrderReference(String orderReference) {
        this.orderReference = orderReference;
    }




}


