package minfin.sandbox.model;
// Generated 7 avr. 2026, 16:25:34 by Hibernate Tools 7.3.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * DgEntityAmount generated by hbm2java
 */
@Entity
@Table(name="DG_ENTITY_AMOUNT"
)
public class DgEntityAmount  implements java.io.Serializable {


     private int id;
     @JsonBackReference
     private FedEntity fedEntity;
     private int amountMonth;
     private BigDecimal residentsLodgingCost;
     private BigDecimal residentsDoctorCost;
     private BigDecimal residentsMedicationCost;
     private BigDecimal residentsOtherFees;
     private BigDecimal subsidyLodgingCost;
     private BigDecimal subsidyStafCost;
     private BigDecimal subsidyMobilityAid;
     private BigDecimal regularizationLodgingCost;
     private BigDecimal regularizationStafCost;
     private BigDecimal regularizationMobilityAid;

    public DgEntityAmount() {
    }

	
    public DgEntityAmount(int id, FedEntity fedEntity, int amountMonth) {
        this.id = id;
        this.fedEntity = fedEntity;
        this.amountMonth = amountMonth;
    }
    public DgEntityAmount(int id, FedEntity fedEntity, int amountMonth, BigDecimal residentsLodgingCost, BigDecimal residentsDoctorCost, BigDecimal residentsMedicationCost, BigDecimal residentsOtherFees, BigDecimal subsidyLodgingCost, BigDecimal subsidyStafCost, BigDecimal subsidyMobilityAid, BigDecimal regularizationLodgingCost, BigDecimal regularizationStafCost, BigDecimal regularizationMobilityAid) {
       this.id = id;
       this.fedEntity = fedEntity;
       this.amountMonth = amountMonth;
       this.residentsLodgingCost = residentsLodgingCost;
       this.residentsDoctorCost = residentsDoctorCost;
       this.residentsMedicationCost = residentsMedicationCost;
       this.residentsOtherFees = residentsOtherFees;
       this.subsidyLodgingCost = subsidyLodgingCost;
       this.subsidyStafCost = subsidyStafCost;
       this.subsidyMobilityAid = subsidyMobilityAid;
       this.regularizationLodgingCost = regularizationLodgingCost;
       this.regularizationStafCost = regularizationStafCost;
       this.regularizationMobilityAid = regularizationMobilityAid;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_FED_ENTITY", nullable=false)
    public FedEntity getFedEntity() {
        return this.fedEntity;
    }
    
    public void setFedEntity(FedEntity fedEntity) {
        this.fedEntity = fedEntity;
    }

    
    @Column(name="AMOUNT_MONTH", nullable=false)
    public int getAmountMonth() {
        return this.amountMonth;
    }
    
    public void setAmountMonth(int amountMonth) {
        this.amountMonth = amountMonth;
    }

    
    @Column(name="RESIDENTS_LODGING_COST", precision=14, scale=2)
    public BigDecimal getResidentsLodgingCost() {
        return this.residentsLodgingCost;
    }
    
    public void setResidentsLodgingCost(BigDecimal residentsLodgingCost) {
        this.residentsLodgingCost = residentsLodgingCost;
    }

    
    @Column(name="RESIDENTS_DOCTOR_COST", precision=14, scale=2)
    public BigDecimal getResidentsDoctorCost() {
        return this.residentsDoctorCost;
    }
    
    public void setResidentsDoctorCost(BigDecimal residentsDoctorCost) {
        this.residentsDoctorCost = residentsDoctorCost;
    }

    
    @Column(name="RESIDENTS_MEDICATION_COST", precision=14, scale=2)
    public BigDecimal getResidentsMedicationCost() {
        return this.residentsMedicationCost;
    }
    
    public void setResidentsMedicationCost(BigDecimal residentsMedicationCost) {
        this.residentsMedicationCost = residentsMedicationCost;
    }

    
    @Column(name="RESIDENTS_OTHER_FEES", precision=14, scale=2)
    public BigDecimal getResidentsOtherFees() {
        return this.residentsOtherFees;
    }
    
    public void setResidentsOtherFees(BigDecimal residentsOtherFees) {
        this.residentsOtherFees = residentsOtherFees;
    }

    
    @Column(name="SUBSIDY_LODGING_COST", precision=14, scale=2)
    public BigDecimal getSubsidyLodgingCost() {
        return this.subsidyLodgingCost;
    }
    
    public void setSubsidyLodgingCost(BigDecimal subsidyLodgingCost) {
        this.subsidyLodgingCost = subsidyLodgingCost;
    }

    
    @Column(name="SUBSIDY_STAF_COST", precision=14, scale=2)
    public BigDecimal getSubsidyStafCost() {
        return this.subsidyStafCost;
    }
    
    public void setSubsidyStafCost(BigDecimal subsidyStafCost) {
        this.subsidyStafCost = subsidyStafCost;
    }

    
    @Column(name="SUBSIDY_MOBILITY_AID", precision=14, scale=2)
    public BigDecimal getSubsidyMobilityAid() {
        return this.subsidyMobilityAid;
    }
    
    public void setSubsidyMobilityAid(BigDecimal subsidyMobilityAid) {
        this.subsidyMobilityAid = subsidyMobilityAid;
    }

    
    @Column(name="REGULARIZATION_LODGING_COST", precision=14, scale=2)
    public BigDecimal getRegularizationLodgingCost() {
        return this.regularizationLodgingCost;
    }
    
    public void setRegularizationLodgingCost(BigDecimal regularizationLodgingCost) {
        this.regularizationLodgingCost = regularizationLodgingCost;
    }

    
    @Column(name="REGULARIZATION_STAF_COST", precision=14, scale=2)
    public BigDecimal getRegularizationStafCost() {
        return this.regularizationStafCost;
    }
    
    public void setRegularizationStafCost(BigDecimal regularizationStafCost) {
        this.regularizationStafCost = regularizationStafCost;
    }

    
    @Column(name="REGULARIZATION_MOBILITY_AID", precision=14, scale=2)
    public BigDecimal getRegularizationMobilityAid() {
        return this.regularizationMobilityAid;
    }
    
    public void setRegularizationMobilityAid(BigDecimal regularizationMobilityAid) {
        this.regularizationMobilityAid = regularizationMobilityAid;
    }




}


