package minfin.sandbox.model;
// Generated 7 avr. 2026, 16:25:34 by Hibernate Tools 7.3.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * EAttest generated by hbm2java
 */
@Entity
@Table(name="E_ATTEST"
)
public class EAttest  implements java.io.Serializable {


     private long NIIdx;
     @JsonBackReference
     private ThirdPartyPayer thirdPartyPayer;
     @JsonBackReference
     private InsuranceInstitution insuranceInstitution;
     private int NIYear;
     private int NIMonth;
     private BigDecimal NITotalAmount;
     private BigDecimal NITotalCancelledAmount;
     private BigDecimal NITotalSupAmount;
     private BigDecimal NITotalSupCancelledAmount;

    public EAttest() {
    }

	
    public EAttest(long NIIdx, ThirdPartyPayer thirdPartyPayer, InsuranceInstitution insuranceInstitution, int NIYear, int NIMonth, BigDecimal NITotalAmount, BigDecimal NITotalCancelledAmount) {
        this.NIIdx = NIIdx;
        this.thirdPartyPayer = thirdPartyPayer;
        this.insuranceInstitution = insuranceInstitution;
        this.NIYear = NIYear;
        this.NIMonth = NIMonth;
        this.NITotalAmount = NITotalAmount;
        this.NITotalCancelledAmount = NITotalCancelledAmount;
    }
    public EAttest(long NIIdx, ThirdPartyPayer thirdPartyPayer, InsuranceInstitution insuranceInstitution, int NIYear, int NIMonth, BigDecimal NITotalAmount, BigDecimal NITotalCancelledAmount, BigDecimal NITotalSupAmount, BigDecimal NITotalSupCancelledAmount) {
       this.NIIdx = NIIdx;
       this.thirdPartyPayer = thirdPartyPayer;
       this.insuranceInstitution = insuranceInstitution;
       this.NIYear = NIYear;
       this.NIMonth = NIMonth;
       this.NITotalAmount = NITotalAmount;
       this.NITotalCancelledAmount = NITotalCancelledAmount;
       this.NITotalSupAmount = NITotalSupAmount;
       this.NITotalSupCancelledAmount = NITotalSupCancelledAmount;
    }
   
     @Id 

    
    @Column(name="N_I_IDX", unique=true, nullable=false)
    public long getNIIdx() {
        return this.NIIdx;
    }
    
    public void setNIIdx(long NIIdx) {
        this.NIIdx = NIIdx;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="N_IDF_THIRD_PARTY_PAYER", nullable=false)
    public ThirdPartyPayer getThirdPartyPayer() {
        return this.thirdPartyPayer;
    }
    
    public void setThirdPartyPayer(ThirdPartyPayer thirdPartyPayer) {
        this.thirdPartyPayer = thirdPartyPayer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="C_INSURANCE_INSTITUTION", nullable=false)
    public InsuranceInstitution getInsuranceInstitution() {
        return this.insuranceInstitution;
    }
    
    public void setInsuranceInstitution(InsuranceInstitution insuranceInstitution) {
        this.insuranceInstitution = insuranceInstitution;
    }

    
    @Column(name="N_I_YEAR", nullable=false)
    public int getNIYear() {
        return this.NIYear;
    }
    
    public void setNIYear(int NIYear) {
        this.NIYear = NIYear;
    }

    
    @Column(name="N_I_MONTH", nullable=false)
    public int getNIMonth() {
        return this.NIMonth;
    }
    
    public void setNIMonth(int NIMonth) {
        this.NIMonth = NIMonth;
    }

    
    @Column(name="N_I_TOTAL_AMOUNT", nullable=false, precision=14, scale=2)
    public BigDecimal getNITotalAmount() {
        return this.NITotalAmount;
    }
    
    public void setNITotalAmount(BigDecimal NITotalAmount) {
        this.NITotalAmount = NITotalAmount;
    }

    
    @Column(name="N_I_TOTAL_CANCELLED_AMOUNT", nullable=false, precision=14, scale=2)
    public BigDecimal getNITotalCancelledAmount() {
        return this.NITotalCancelledAmount;
    }
    
    public void setNITotalCancelledAmount(BigDecimal NITotalCancelledAmount) {
        this.NITotalCancelledAmount = NITotalCancelledAmount;
    }

    
    @Column(name="N_I_TOTAL_SUP_AMOUNT", precision=12, scale=2)
    public BigDecimal getNITotalSupAmount() {
        return this.NITotalSupAmount;
    }
    
    public void setNITotalSupAmount(BigDecimal NITotalSupAmount) {
        this.NITotalSupAmount = NITotalSupAmount;
    }

    
    @Column(name="N_I_TOTAL_SUP_CANCELLED_AMOUNT", precision=12, scale=2)
    public BigDecimal getNITotalSupCancelledAmount() {
        return this.NITotalSupCancelledAmount;
    }
    
    public void setNITotalSupCancelledAmount(BigDecimal NITotalSupCancelledAmount) {
        this.NITotalSupCancelledAmount = NITotalSupCancelledAmount;
    }




}


