package minfin.sandbox.model;
// Generated 7 avr. 2026, 16:25:34 by Hibernate Tools 7.3.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * FedEntity generated by hbm2java
 */
@Entity
@Table(name="FED_ENTITY"
)
public class FedEntity  implements java.io.Serializable {


     private int id;
     @JsonBackReference
     private ThirdPartyPayer thirdPartyPayer;
     private int fentityYear;
     private String hco;
     private String entityType;
     @JsonManagedReference
     private Set<VlEntityAmount> vlEntityAmounts = new HashSet<VlEntityAmount>(0);
     @JsonManagedReference
     private Set<FwbEntityAmount> fwbEntityAmounts = new HashSet<FwbEntityAmount>(0);
     @JsonManagedReference
     private Set<BxEntityAmount> bxEntityAmounts = new HashSet<BxEntityAmount>(0);
     @JsonManagedReference
     private Set<DgEntityAmount> dgEntityAmounts = new HashSet<DgEntityAmount>(0);
     @JsonManagedReference
     private Set<RwEntityAmount> rwEntityAmounts = new HashSet<RwEntityAmount>(0);

    public FedEntity() {
    }

	
    public FedEntity(int id, ThirdPartyPayer thirdPartyPayer, int fentityYear) {
        this.id = id;
        this.thirdPartyPayer = thirdPartyPayer;
        this.fentityYear = fentityYear;
    }
    public FedEntity(int id, ThirdPartyPayer thirdPartyPayer, int fentityYear, String hco, String entityType, Set<VlEntityAmount> vlEntityAmounts, Set<FwbEntityAmount> fwbEntityAmounts, Set<BxEntityAmount> bxEntityAmounts, Set<DgEntityAmount> dgEntityAmounts, Set<RwEntityAmount> rwEntityAmounts) {
       this.id = id;
       this.thirdPartyPayer = thirdPartyPayer;
       this.fentityYear = fentityYear;
       this.hco = hco;
       this.entityType = entityType;
       this.vlEntityAmounts = vlEntityAmounts;
       this.fwbEntityAmounts = fwbEntityAmounts;
       this.bxEntityAmounts = bxEntityAmounts;
       this.dgEntityAmounts = dgEntityAmounts;
       this.rwEntityAmounts = rwEntityAmounts;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDF_THIRD_PARTY_PAYER", nullable=false)
    public ThirdPartyPayer getThirdPartyPayer() {
        return this.thirdPartyPayer;
    }
    
    public void setThirdPartyPayer(ThirdPartyPayer thirdPartyPayer) {
        this.thirdPartyPayer = thirdPartyPayer;
    }

    
    @Column(name="FENTITY_YEAR", nullable=false)
    public int getFentityYear() {
        return this.fentityYear;
    }
    
    public void setFentityYear(int fentityYear) {
        this.fentityYear = fentityYear;
    }

    
    @Column(name="HCO", length=30)
    public String getHco() {
        return this.hco;
    }
    
    public void setHco(String hco) {
        this.hco = hco;
    }

    
    @Column(name="ENTITY_TYPE", length=3)
    public String getEntityType() {
        return this.entityType;
    }
    
    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fedEntity")
    public Set<VlEntityAmount> getVlEntityAmounts() {
        return this.vlEntityAmounts;
    }
    
    public void setVlEntityAmounts(Set<VlEntityAmount> vlEntityAmounts) {
        this.vlEntityAmounts = vlEntityAmounts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fedEntity")
    public Set<FwbEntityAmount> getFwbEntityAmounts() {
        return this.fwbEntityAmounts;
    }
    
    public void setFwbEntityAmounts(Set<FwbEntityAmount> fwbEntityAmounts) {
        this.fwbEntityAmounts = fwbEntityAmounts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fedEntity")
    public Set<BxEntityAmount> getBxEntityAmounts() {
        return this.bxEntityAmounts;
    }
    
    public void setBxEntityAmounts(Set<BxEntityAmount> bxEntityAmounts) {
        this.bxEntityAmounts = bxEntityAmounts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fedEntity")
    public Set<DgEntityAmount> getDgEntityAmounts() {
        return this.dgEntityAmounts;
    }
    
    public void setDgEntityAmounts(Set<DgEntityAmount> dgEntityAmounts) {
        this.dgEntityAmounts = dgEntityAmounts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fedEntity")
    public Set<RwEntityAmount> getRwEntityAmounts() {
        return this.rwEntityAmounts;
    }
    
    public void setRwEntityAmounts(Set<RwEntityAmount> rwEntityAmounts) {
        this.rwEntityAmounts = rwEntityAmounts;
    }




}


