package minfin.sandbox.model;
// Generated 7 avr. 2026, 16:25:34 by Hibernate Tools 7.3.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * InsuranceInstitution generated by hbm2java
 */
@Entity
@Table(name="INSURANCE_INSTITUTION"
)
public class InsuranceInstitution  implements java.io.Serializable {

    @JsonBackReference
     private long insuranceInstitutionNumber;
     private String nameFr;
     private String nameNl;
     @JsonManagedReference
     private Set<VlEntityAmount> vlEntityAmounts = new HashSet<VlEntityAmount>(0);
     @JsonManagedReference
     private Set<InvoiceNotification> invoiceNotifications = new HashSet<InvoiceNotification>(0);
     @JsonManagedReference
     private Set<BxEntityAmount> bxEntityAmounts = new HashSet<BxEntityAmount>(0);
     @JsonManagedReference
     private Set<FwbEntityAmount> fwbEntityAmounts = new HashSet<FwbEntityAmount>(0);
     @JsonManagedReference
     private Set<RwEntityAmount> rwEntityAmounts = new HashSet<RwEntityAmount>(0);
     @JsonManagedReference
     private Set<EAttest> EAttests = new HashSet<EAttest>(0);

    public InsuranceInstitution() {
    }

	
    public InsuranceInstitution(long insuranceInstitutionNumber, String nameFr, String nameNl) {
        this.insuranceInstitutionNumber = insuranceInstitutionNumber;
        this.nameFr = nameFr;
        this.nameNl = nameNl;
    }
    public InsuranceInstitution(long insuranceInstitutionNumber, String nameFr, String nameNl, Set<VlEntityAmount> vlEntityAmounts, Set<InvoiceNotification> invoiceNotifications, Set<BxEntityAmount> bxEntityAmounts, Set<FwbEntityAmount> fwbEntityAmounts, Set<RwEntityAmount> rwEntityAmounts, Set<EAttest> EAttests) {
       this.insuranceInstitutionNumber = insuranceInstitutionNumber;
       this.nameFr = nameFr;
       this.nameNl = nameNl;
       this.vlEntityAmounts = vlEntityAmounts;
       this.invoiceNotifications = invoiceNotifications;
       this.bxEntityAmounts = bxEntityAmounts;
       this.fwbEntityAmounts = fwbEntityAmounts;
       this.rwEntityAmounts = rwEntityAmounts;
       this.EAttests = EAttests;
    }
   
     @Id 

    
    @Column(name="INSURANCE_INSTITUTION_NUMBER", unique=true, nullable=false)
    public long getInsuranceInstitutionNumber() {
        return this.insuranceInstitutionNumber;
    }
    
    public void setInsuranceInstitutionNumber(long insuranceInstitutionNumber) {
        this.insuranceInstitutionNumber = insuranceInstitutionNumber;
    }

    
    @Column(name="NAME_FR", nullable=false, length=255)
    public String getNameFr() {
        return this.nameFr;
    }
    
    public void setNameFr(String nameFr) {
        this.nameFr = nameFr;
    }

    
    @Column(name="NAME_NL", nullable=false, length=255)
    public String getNameNl() {
        return this.nameNl;
    }
    
    public void setNameNl(String nameNl) {
        this.nameNl = nameNl;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="insuranceInstitution")
    public Set<VlEntityAmount> getVlEntityAmounts() {
        return this.vlEntityAmounts;
    }
    
    public void setVlEntityAmounts(Set<VlEntityAmount> vlEntityAmounts) {
        this.vlEntityAmounts = vlEntityAmounts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="insuranceInstitution")
    public Set<InvoiceNotification> getInvoiceNotifications() {
        return this.invoiceNotifications;
    }
    
    public void setInvoiceNotifications(Set<InvoiceNotification> invoiceNotifications) {
        this.invoiceNotifications = invoiceNotifications;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="insuranceInstitution")
    public Set<BxEntityAmount> getBxEntityAmounts() {
        return this.bxEntityAmounts;
    }
    
    public void setBxEntityAmounts(Set<BxEntityAmount> bxEntityAmounts) {
        this.bxEntityAmounts = bxEntityAmounts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="insuranceInstitution")
    public Set<FwbEntityAmount> getFwbEntityAmounts() {
        return this.fwbEntityAmounts;
    }
    
    public void setFwbEntityAmounts(Set<FwbEntityAmount> fwbEntityAmounts) {
        this.fwbEntityAmounts = fwbEntityAmounts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="insuranceInstitution")
    public Set<RwEntityAmount> getRwEntityAmounts() {
        return this.rwEntityAmounts;
    }
    
    public void setRwEntityAmounts(Set<RwEntityAmount> rwEntityAmounts) {
        this.rwEntityAmounts = rwEntityAmounts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="insuranceInstitution")
    public Set<EAttest> getEAttests() {
        return this.EAttests;
    }
    
    public void setEAttests(Set<EAttest> EAttests) {
        this.EAttests = EAttests;
    }




}


