package minfin.sandbox.model;
// Generated 7 avr. 2026, 16:25:34 by Hibernate Tools 7.3.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * InvoiceInformation generated by hbm2java
 */
@Entity
@Table(name="INVOICE_INFORMATION"
)
public class InvoiceInformation  implements java.io.Serializable {


     private long idf;
     @JsonBackReference
     private InvoiceNotification invoiceNotification;
     @JsonBackReference
     private AccountType accountType;
     private BigDecimal invoicedAmount;
     private BigDecimal totalPaymentAmount;
     private BigDecimal supplementAmount;
     private BigDecimal interventionPersoAmount;
     @JsonManagedReference
     private Set<PaymentInformation> paymentInformations = new HashSet<PaymentInformation>(0);

    public InvoiceInformation() {
    }

	
    public InvoiceInformation(long idf, InvoiceNotification invoiceNotification, AccountType accountType, BigDecimal invoicedAmount, BigDecimal totalPaymentAmount) {
        this.idf = idf;
        this.invoiceNotification = invoiceNotification;
        this.accountType = accountType;
        this.invoicedAmount = invoicedAmount;
        this.totalPaymentAmount = totalPaymentAmount;
    }
    public InvoiceInformation(long idf, InvoiceNotification invoiceNotification, AccountType accountType, BigDecimal invoicedAmount, BigDecimal totalPaymentAmount, BigDecimal supplementAmount, BigDecimal interventionPersoAmount, Set<PaymentInformation> paymentInformations) {
       this.idf = idf;
       this.invoiceNotification = invoiceNotification;
       this.accountType = accountType;
       this.invoicedAmount = invoicedAmount;
       this.totalPaymentAmount = totalPaymentAmount;
       this.supplementAmount = supplementAmount;
       this.interventionPersoAmount = interventionPersoAmount;
       this.paymentInformations = paymentInformations;
    }
   
     @Id 

    
    @Column(name="IDF", unique=true, nullable=false)
    public long getIdf() {
        return this.idf;
    }
    
    public void setIdf(long idf) {
        this.idf = idf;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="INVOICE_NOTIFICATION", nullable=false)
    public InvoiceNotification getInvoiceNotification() {
        return this.invoiceNotification;
    }
    
    public void setInvoiceNotification(InvoiceNotification invoiceNotification) {
        this.invoiceNotification = invoiceNotification;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACCOUNT_TYPE", nullable=false)
    public AccountType getAccountType() {
        return this.accountType;
    }
    
    public void setAccountType(AccountType accountType) {
        this.accountType = accountType;
    }

    
    @Column(name="INVOICED_AMOUNT", nullable=false, precision=12, scale=2)
    public BigDecimal getInvoicedAmount() {
        return this.invoicedAmount;
    }
    
    public void setInvoicedAmount(BigDecimal invoicedAmount) {
        this.invoicedAmount = invoicedAmount;
    }

    
    @Column(name="TOTAL_PAYMENT_AMOUNT", nullable=false, precision=12, scale=2)
    public BigDecimal getTotalPaymentAmount() {
        return this.totalPaymentAmount;
    }
    
    public void setTotalPaymentAmount(BigDecimal totalPaymentAmount) {
        this.totalPaymentAmount = totalPaymentAmount;
    }

    
    @Column(name="SUPPLEMENT_AMOUNT", precision=12, scale=2)
    public BigDecimal getSupplementAmount() {
        return this.supplementAmount;
    }
    
    public void setSupplementAmount(BigDecimal supplementAmount) {
        this.supplementAmount = supplementAmount;
    }

    
    @Column(name="INTERVENTION_PERSO_AMOUNT", precision=12, scale=2)
    public BigDecimal getInterventionPersoAmount() {
        return this.interventionPersoAmount;
    }
    
    public void setInterventionPersoAmount(BigDecimal interventionPersoAmount) {
        this.interventionPersoAmount = interventionPersoAmount;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="invoiceInformation")
    public Set<PaymentInformation> getPaymentInformations() {
        return this.paymentInformations;
    }
    
    public void setPaymentInformations(Set<PaymentInformation> paymentInformations) {
        this.paymentInformations = paymentInformations;
    }




}


