package minfin.sandbox.model;
// Generated 7 avr. 2026, 16:25:34 by Hibernate Tools 7.3.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * InvoiceNotification generated by hbm2java
 */
@Entity
@Table(name="INVOICE_NOTIFICATION"
)
public class InvoiceNotification  implements java.io.Serializable {


     private long idf;
     @JsonBackReference
     private ThirdPartyPayer thirdPartyPayer;
     @JsonBackReference
     private InsuranceInstitution insuranceInstitution;
     private int invoiceYear;
     private int invoiceMonth;
     @JsonManagedReference
     private Set<InvoiceInformation> invoiceInformations = new HashSet<InvoiceInformation>(0);

    public InvoiceNotification() {
    }

	
    public InvoiceNotification(long idf, ThirdPartyPayer thirdPartyPayer, InsuranceInstitution insuranceInstitution, int invoiceYear, int invoiceMonth) {
        this.idf = idf;
        this.thirdPartyPayer = thirdPartyPayer;
        this.insuranceInstitution = insuranceInstitution;
        this.invoiceYear = invoiceYear;
        this.invoiceMonth = invoiceMonth;
    }
    public InvoiceNotification(long idf, ThirdPartyPayer thirdPartyPayer, InsuranceInstitution insuranceInstitution, int invoiceYear, int invoiceMonth, Set<InvoiceInformation> invoiceInformations) {
       this.idf = idf;
       this.thirdPartyPayer = thirdPartyPayer;
       this.insuranceInstitution = insuranceInstitution;
       this.invoiceYear = invoiceYear;
       this.invoiceMonth = invoiceMonth;
       this.invoiceInformations = invoiceInformations;
    }
   
     @Id 

    
    @Column(name="IDF", unique=true, nullable=false)
    public long getIdf() {
        return this.idf;
    }
    
    public void setIdf(long idf) {
        this.idf = idf;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDF_THIRD_PARTY_PAYER", nullable=false)
    public ThirdPartyPayer getThirdPartyPayer() {
        return this.thirdPartyPayer;
    }
    
    public void setThirdPartyPayer(ThirdPartyPayer thirdPartyPayer) {
        this.thirdPartyPayer = thirdPartyPayer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="INSURANCE_INSTITUTION_NUMBER", nullable=false)
    public InsuranceInstitution getInsuranceInstitution() {
        return this.insuranceInstitution;
    }
    
    public void setInsuranceInstitution(InsuranceInstitution insuranceInstitution) {
        this.insuranceInstitution = insuranceInstitution;
    }

    
    @Column(name="INVOICE_YEAR", nullable=false)
    public int getInvoiceYear() {
        return this.invoiceYear;
    }
    
    public void setInvoiceYear(int invoiceYear) {
        this.invoiceYear = invoiceYear;
    }

    
    @Column(name="INVOICE_MONTH", nullable=false)
    public int getInvoiceMonth() {
        return this.invoiceMonth;
    }
    
    public void setInvoiceMonth(int invoiceMonth) {
        this.invoiceMonth = invoiceMonth;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="invoiceNotification")
    public Set<InvoiceInformation> getInvoiceInformations() {
        return this.invoiceInformations;
    }
    
    public void setInvoiceInformations(Set<InvoiceInformation> invoiceInformations) {
        this.invoiceInformations = invoiceInformations;
    }




}


