package minfin.sandbox.model;
// Generated 7 avr. 2026, 16:25:34 by Hibernate Tools 7.3.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.UniqueConstraint;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * LogBatchs generated by hbm2java
 */
@Entity
@Table(name="LOG_BATCHS"
    , uniqueConstraints = @UniqueConstraint(columnNames={"TASK_ID", "START_DATE"}) 
)
public class LogBatchs  implements java.io.Serializable {


     private long id;
     private Date startDate;
     private String typeName;
     private String fileName;
     private Long taskId;
     private String status;
     private Date statusDate;
     private Long previousId;
     private Blob datas;
     @JsonManagedReference
     private Set<LogErrorBatchs> logErrorBatchses = new HashSet<LogErrorBatchs>(0);

    public LogBatchs() {
    }

	
    public LogBatchs(long id) {
        this.id = id;
    }
    public LogBatchs(long id, Date startDate, String typeName, String fileName, Long taskId, String status, Date statusDate, Long previousId, Blob datas, Set<LogErrorBatchs> logErrorBatchses) {
       this.id = id;
       this.startDate = startDate;
       this.typeName = typeName;
       this.fileName = fileName;
       this.taskId = taskId;
       this.status = status;
       this.statusDate = statusDate;
       this.previousId = previousId;
       this.datas = datas;
       this.logErrorBatchses = logErrorBatchses;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="START_DATE", length=26)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    
    @Column(name="TYPE_NAME", length=255)
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    
    @Column(name="FILE_NAME", length=255)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="TASK_ID")
    public Long getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    
    @Column(name="STATUS", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="STATUS_DATE", length=26)
    public Date getStatusDate() {
        return this.statusDate;
    }
    
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

    
    @Column(name="PREVIOUS_ID")
    public Long getPreviousId() {
        return this.previousId;
    }
    
    public void setPreviousId(Long previousId) {
        this.previousId = previousId;
    }

    
    @Column(name="DATAS")
    public Blob getDatas() {
        return this.datas;
    }
    
    public void setDatas(Blob datas) {
        this.datas = datas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="logBatchs")
    public Set<LogErrorBatchs> getLogErrorBatchses() {
        return this.logErrorBatchses;
    }
    
    public void setLogErrorBatchses(Set<LogErrorBatchs> logErrorBatchses) {
        this.logErrorBatchses = logErrorBatchses;
    }




}


