package minfin.sandbox.model;
// Generated 7 avr. 2026, 16:25:34 by Hibernate Tools 7.3.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.util.Date;

/**
 * LogErrorBatchs generated by hbm2java
 */
@Entity
@Table(name="LOG_ERROR_BATCHS"
)
public class LogErrorBatchs  implements java.io.Serializable {


     private long id;
     private LogBatchs logBatchs;
     private Date dateBatch;
     private Integer errorCode;
     private String ligneComplete;
     private String errorMessage;

    public LogErrorBatchs() {
    }

	
    public LogErrorBatchs(long id) {
        this.id = id;
    }
    public LogErrorBatchs(long id, LogBatchs logBatchs, Date dateBatch, Integer errorCode, String ligneComplete, String errorMessage) {
       this.id = id;
       this.logBatchs = logBatchs;
       this.dateBatch = dateBatch;
       this.errorCode = errorCode;
       this.ligneComplete = ligneComplete;
       this.errorMessage = errorMessage;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BATCH_ID")
    public LogBatchs getLogBatchs() {
        return this.logBatchs;
    }
    
    public void setLogBatchs(LogBatchs logBatchs) {
        this.logBatchs = logBatchs;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_BATCH", length=10)
    public Date getDateBatch() {
        return this.dateBatch;
    }
    
    public void setDateBatch(Date dateBatch) {
        this.dateBatch = dateBatch;
    }

    
    @Column(name="ERROR_CODE")
    public Integer getErrorCode() {
        return this.errorCode;
    }
    
    public void setErrorCode(Integer errorCode) {
        this.errorCode = errorCode;
    }

    
    @Column(name="LIGNE_COMPLETE", length=255)
    public String getLigneComplete() {
        return this.ligneComplete;
    }
    
    public void setLigneComplete(String ligneComplete) {
        this.ligneComplete = ligneComplete;
    }

    
    @Column(name="ERROR_MESSAGE", length=255)
    public String getErrorMessage() {
        return this.errorMessage;
    }
    
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }




}


