package minfin.sandbox.model;
// Generated 7 avr. 2026, 16:25:34 by Hibernate Tools 7.3.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * MaPrest002UixV generated by hbm2java
 */
@Entity
@Table(name="MA_PREST002_UIX_V"
)
public class MaPrest002UixV  implements java.io.Serializable {


     private String k00;

    public MaPrest002UixV() {
    }

    public MaPrest002UixV(String k00) {
       this.k00 = k00;
    }
   
     @Id 

    
    @Column(name="K00", nullable=false, length=8)
    public String getK00() {
        return this.k00;
    }
    
    public void setK00(String k00) {
        this.k00 = k00;
    }




}


