package minfin.sandbox.model;
// Generated 7 avr. 2026, 16:25:34 by Hibernate Tools 7.3.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * PaperType generated by hbm2java
 */
@Entity
@Table(name="PAPER_TYPE"
)
public class PaperType  implements java.io.Serializable {


     private int id;
     private String code;
     private String labelFr;
     private String labelNl;

    public PaperType() {
    }

	
    public PaperType(int id, String code) {
        this.id = id;
        this.code = code;
    }
    public PaperType(int id, String code, String labelFr, String labelNl) {
       this.id = id;
       this.code = code;
       this.labelFr = labelFr;
       this.labelNl = labelNl;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="CODE", nullable=false, length=3)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="LABEL_FR", length=255)
    public String getLabelFr() {
        return this.labelFr;
    }
    
    public void setLabelFr(String labelFr) {
        this.labelFr = labelFr;
    }

    
    @Column(name="LABEL_NL", length=255)
    public String getLabelNl() {
        return this.labelNl;
    }
    
    public void setLabelNl(String labelNl) {
        this.labelNl = labelNl;
    }




}


