package minfin.sandbox.model;
// Generated 7 avr. 2026, 16:25:34 by Hibernate Tools 7.3.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * PaperOrder generated by hbm2java
 */
@Entity
@Table(name="PAPER_ORDER"
)
public class PaperOrder  implements java.io.Serializable {


     private int CIIdx;
     private String TIBce;
     private String TIInami;
     private String TINationalNummer;
     private int CIOrderYear;
     private String TIProductCd;
     private String altNummer;
     private Integer specializationType;
     private Integer orderType;
     @JsonManagedReference
     private Set<BookOrder> bookOrders = new HashSet<BookOrder>(0);

    public PaperOrder() {
    }

	
    public PaperOrder(int CIIdx, int CIOrderYear) {
        this.CIIdx = CIIdx;
        this.CIOrderYear = CIOrderYear;
    }
    public PaperOrder(int CIIdx, String TIBce, String TIInami, String TINationalNummer, int CIOrderYear, String TIProductCd, String altNummer, Integer specializationType, Integer orderType, Set<BookOrder> bookOrders) {
       this.CIIdx = CIIdx;
       this.TIBce = TIBce;
       this.TIInami = TIInami;
       this.TINationalNummer = TINationalNummer;
       this.CIOrderYear = CIOrderYear;
       this.TIProductCd = TIProductCd;
       this.altNummer = altNummer;
       this.specializationType = specializationType;
       this.orderType = orderType;
       this.bookOrders = bookOrders;
    }
   
     @Id 

    
    @Column(name="C_I_IDX", unique=true, nullable=false)
    public int getCIIdx() {
        return this.CIIdx;
    }
    
    public void setCIIdx(int CIIdx) {
        this.CIIdx = CIIdx;
    }

    
    @Column(name="T_I_BCE", length=12)
    public String getTIBce() {
        return this.TIBce;
    }
    
    public void setTIBce(String TIBce) {
        this.TIBce = TIBce;
    }

    
    @Column(name="T_I_INAMI", length=12)
    public String getTIInami() {
        return this.TIInami;
    }
    
    public void setTIInami(String TIInami) {
        this.TIInami = TIInami;
    }

    
    @Column(name="T_I_NATIONAL_NUMMER", length=11)
    public String getTINationalNummer() {
        return this.TINationalNummer;
    }
    
    public void setTINationalNummer(String TINationalNummer) {
        this.TINationalNummer = TINationalNummer;
    }

    
    @Column(name="C_I_ORDER_YEAR", nullable=false)
    public int getCIOrderYear() {
        return this.CIOrderYear;
    }
    
    public void setCIOrderYear(int CIOrderYear) {
        this.CIOrderYear = CIOrderYear;
    }

    
    @Column(name="T_I_PRODUCT_CD", length=3)
    public String getTIProductCd() {
        return this.TIProductCd;
    }
    
    public void setTIProductCd(String TIProductCd) {
        this.TIProductCd = TIProductCd;
    }

    
    @Column(name="ALT_NUMMER", length=30)
    public String getAltNummer() {
        return this.altNummer;
    }
    
    public void setAltNummer(String altNummer) {
        this.altNummer = altNummer;
    }

    
    @Column(name="SPECIALIZATION_TYPE")
    public Integer getSpecializationType() {
        return this.specializationType;
    }
    
    public void setSpecializationType(Integer specializationType) {
        this.specializationType = specializationType;
    }

    
    @Column(name="ORDER_TYPE")
    public Integer getOrderType() {
        return this.orderType;
    }
    
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paperOrder")
    public Set<BookOrder> getBookOrders() {
        return this.bookOrders;
    }
    
    public void setBookOrders(Set<BookOrder> bookOrders) {
        this.bookOrders = bookOrders;
    }




}


