package minfin.sandbox.model;
// Generated 7 avr. 2026, 16:25:34 by Hibernate Tools 7.3.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * PaymentInformation generated by hbm2java
 */
@Entity
@Table(name="PAYMENT_INFORMATION"
)
public class PaymentInformation  implements java.io.Serializable {


     private long idf;
     @JsonBackReference
     private TypePayment typePayment;
     @JsonBackReference
     private InvoiceInformation invoiceInformation;
     private Date date;
     private BigDecimal amount;

    public PaymentInformation() {
    }

    public PaymentInformation(long idf, TypePayment typePayment, InvoiceInformation invoiceInformation, Date date, BigDecimal amount) {
       this.idf = idf;
       this.typePayment = typePayment;
       this.invoiceInformation = invoiceInformation;
       this.date = date;
       this.amount = amount;
    }
   
     @Id 

    
    @Column(name="IDF", unique=true, nullable=false)
    public long getIdf() {
        return this.idf;
    }
    
    public void setIdf(long idf) {
        this.idf = idf;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TYPE_PAYMENT", nullable=false)
    public TypePayment getTypePayment() {
        return this.typePayment;
    }
    
    public void setTypePayment(TypePayment typePayment) {
        this.typePayment = typePayment;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="INVOICE_INFORMATION", nullable=false)
    public InvoiceInformation getInvoiceInformation() {
        return this.invoiceInformation;
    }
    
    public void setInvoiceInformation(InvoiceInformation invoiceInformation) {
        this.invoiceInformation = invoiceInformation;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="AMOUNT", nullable=false, precision=12, scale=2)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }




}


