package minfin.sandbox.model;
// Generated 7 avr. 2026, 16:25:34 by Hibernate Tools 7.3.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * ThirdPartyPayer generated by hbm2java
 */
@Entity
@Table(name="THIRD_PARTY_PAYER"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ENTERPRISE_NUMBER", "NIHDI_NUMBER"}) 
)
public class ThirdPartyPayer  implements java.io.Serializable {


     private long idf;
     private String nihdiNumber;
     private String enterpriseNumber;
     private String persIdf;
     @JsonManagedReference
     private Set<EAttest> EAttests = new HashSet<EAttest>(0);
     @JsonManagedReference
     private Set<FedEntity> fedEntities = new HashSet<FedEntity>(0);
     @JsonManagedReference
     private Set<InvoiceNotification> invoiceNotifications = new HashSet<InvoiceNotification>(0);

    public ThirdPartyPayer() {
    }

	
    public ThirdPartyPayer(long idf, String nihdiNumber, String enterpriseNumber) {
        this.idf = idf;
        this.nihdiNumber = nihdiNumber;
        this.enterpriseNumber = enterpriseNumber;
    }
    public ThirdPartyPayer(long idf, String nihdiNumber, String enterpriseNumber, String persIdf, Set<EAttest> EAttests, Set<FedEntity> fedEntities, Set<InvoiceNotification> invoiceNotifications) {
       this.idf = idf;
       this.nihdiNumber = nihdiNumber;
       this.enterpriseNumber = enterpriseNumber;
       this.persIdf = persIdf;
       this.EAttests = EAttests;
       this.fedEntities = fedEntities;
       this.invoiceNotifications = invoiceNotifications;
    }
   
     @Id 

    
    @Column(name="IDF", unique=true, nullable=false)
    public long getIdf() {
        return this.idf;
    }
    
    public void setIdf(long idf) {
        this.idf = idf;
    }

    
    @Column(name="NIHDI_NUMBER", nullable=false, length=11)
    public String getNihdiNumber() {
        return this.nihdiNumber;
    }
    
    public void setNihdiNumber(String nihdiNumber) {
        this.nihdiNumber = nihdiNumber;
    }

    
    @Column(name="ENTERPRISE_NUMBER", nullable=false, length=10)
    public String getEnterpriseNumber() {
        return this.enterpriseNumber;
    }
    
    public void setEnterpriseNumber(String enterpriseNumber) {
        this.enterpriseNumber = enterpriseNumber;
    }

    
    @Column(name="PERS_IDF", length=12)
    public String getPersIdf() {
        return this.persIdf;
    }
    
    public void setPersIdf(String persIdf) {
        this.persIdf = persIdf;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="thirdPartyPayer")
    public Set<EAttest> getEAttests() {
        return this.EAttests;
    }
    
    public void setEAttests(Set<EAttest> EAttests) {
        this.EAttests = EAttests;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="thirdPartyPayer")
    public Set<FedEntity> getFedEntities() {
        return this.fedEntities;
    }
    
    public void setFedEntities(Set<FedEntity> fedEntities) {
        this.fedEntities = fedEntities;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="thirdPartyPayer")
    public Set<InvoiceNotification> getInvoiceNotifications() {
        return this.invoiceNotifications;
    }
    
    public void setInvoiceNotifications(Set<InvoiceNotification> invoiceNotifications) {
        this.invoiceNotifications = invoiceNotifications;
    }




}


