package minfin.sandbox.model;
// Generated 7 avr. 2026, 16:25:34 by Hibernate Tools 7.3.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TypePayment generated by hbm2java
 */
@Entity
@Table(name="TYPE_PAYMENT"
)
public class TypePayment  implements java.io.Serializable {


     private long idf;
     private String name;
     private String nameFr;
     private String nameNl;
     @JsonManagedReference
     private Set<PaymentInformation> paymentInformations = new HashSet<PaymentInformation>(0);

    public TypePayment() {
    }

	
    public TypePayment(long idf) {
        this.idf = idf;
    }
    public TypePayment(long idf, String name, String nameFr, String nameNl, Set<PaymentInformation> paymentInformations) {
       this.idf = idf;
       this.name = name;
       this.nameFr = nameFr;
       this.nameNl = nameNl;
       this.paymentInformations = paymentInformations;
    }
   
     @Id 

    
    @Column(name="IDF", unique=true, nullable=false)
    public long getIdf() {
        return this.idf;
    }
    
    public void setIdf(long idf) {
        this.idf = idf;
    }

    
    @Column(name="NAME", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="NAME_FR", length=255)
    public String getNameFr() {
        return this.nameFr;
    }
    
    public void setNameFr(String nameFr) {
        this.nameFr = nameFr;
    }

    
    @Column(name="NAME_NL", length=255)
    public String getNameNl() {
        return this.nameNl;
    }
    
    public void setNameNl(String nameNl) {
        this.nameNl = nameNl;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="typePayment")
    public Set<PaymentInformation> getPaymentInformations() {
        return this.paymentInformations;
    }
    
    public void setPaymentInformations(Set<PaymentInformation> paymentInformations) {
        this.paymentInformations = paymentInformations;
    }




}


