package minfin.sandbox.model;
// Generated 7 avr. 2026, 16:25:34 by Hibernate Tools 7.3.0.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * VlEntityAmount generated by hbm2java
 */
@Entity
@Table(name="VL_ENTITY_AMOUNT"
)
public class VlEntityAmount  implements java.io.Serializable {


     private int id;
     private FedEntity fedEntity;
     @JsonBackReference
     private InsuranceInstitution insuranceInstitution;
     private int amountMonth;
     private Integer amountType;
     private BigDecimal residentsLodgingCost;
     private BigDecimal residentsOtherFees;
     private BigDecimal residentsThirdPartyFees;
     private BigDecimal invoiceAmount;
     private BigDecimal paymentAmount;
     private Date paymentDate;

    public VlEntityAmount() {
    }

	
    public VlEntityAmount(int id, FedEntity fedEntity, InsuranceInstitution insuranceInstitution, int amountMonth) {
        this.id = id;
        this.fedEntity = fedEntity;
        this.insuranceInstitution = insuranceInstitution;
        this.amountMonth = amountMonth;
    }
    public VlEntityAmount(int id, FedEntity fedEntity, InsuranceInstitution insuranceInstitution, int amountMonth, Integer amountType, BigDecimal residentsLodgingCost, BigDecimal residentsOtherFees, BigDecimal residentsThirdPartyFees, BigDecimal invoiceAmount, BigDecimal paymentAmount, Date paymentDate) {
       this.id = id;
       this.fedEntity = fedEntity;
       this.insuranceInstitution = insuranceInstitution;
       this.amountMonth = amountMonth;
       this.amountType = amountType;
       this.residentsLodgingCost = residentsLodgingCost;
       this.residentsOtherFees = residentsOtherFees;
       this.residentsThirdPartyFees = residentsThirdPartyFees;
       this.invoiceAmount = invoiceAmount;
       this.paymentAmount = paymentAmount;
       this.paymentDate = paymentDate;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_FED_ENTITY", nullable=false)
    public FedEntity getFedEntity() {
        return this.fedEntity;
    }
    
    public void setFedEntity(FedEntity fedEntity) {
        this.fedEntity = fedEntity;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="INSURANCE_INSTITUTION", nullable=false)
    public InsuranceInstitution getInsuranceInstitution() {
        return this.insuranceInstitution;
    }
    
    public void setInsuranceInstitution(InsuranceInstitution insuranceInstitution) {
        this.insuranceInstitution = insuranceInstitution;
    }

    
    @Column(name="AMOUNT_MONTH", nullable=false)
    public int getAmountMonth() {
        return this.amountMonth;
    }
    
    public void setAmountMonth(int amountMonth) {
        this.amountMonth = amountMonth;
    }

    
    @Column(name="AMOUNT_TYPE")
    public Integer getAmountType() {
        return this.amountType;
    }
    
    public void setAmountType(Integer amountType) {
        this.amountType = amountType;
    }

    
    @Column(name="RESIDENTS_LODGING_COST", precision=14, scale=2)
    public BigDecimal getResidentsLodgingCost() {
        return this.residentsLodgingCost;
    }
    
    public void setResidentsLodgingCost(BigDecimal residentsLodgingCost) {
        this.residentsLodgingCost = residentsLodgingCost;
    }

    
    @Column(name="RESIDENTS_OTHER_FEES", precision=14, scale=2)
    public BigDecimal getResidentsOtherFees() {
        return this.residentsOtherFees;
    }
    
    public void setResidentsOtherFees(BigDecimal residentsOtherFees) {
        this.residentsOtherFees = residentsOtherFees;
    }

    
    @Column(name="RESIDENTS_THIRD_PARTY_FEES", precision=14, scale=2)
    public BigDecimal getResidentsThirdPartyFees() {
        return this.residentsThirdPartyFees;
    }
    
    public void setResidentsThirdPartyFees(BigDecimal residentsThirdPartyFees) {
        this.residentsThirdPartyFees = residentsThirdPartyFees;
    }

    
    @Column(name="INVOICE_AMOUNT", precision=14, scale=2)
    public BigDecimal getInvoiceAmount() {
        return this.invoiceAmount;
    }
    
    public void setInvoiceAmount(BigDecimal invoiceAmount) {
        this.invoiceAmount = invoiceAmount;
    }

    
    @Column(name="PAYMENT_AMOUNT", precision=14, scale=2)
    public BigDecimal getPaymentAmount() {
        return this.paymentAmount;
    }
    
    public void setPaymentAmount(BigDecimal paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PAYMENT_DATE", length=10)
    public Date getPaymentDate() {
        return this.paymentDate;
    }
    
    public void setPaymentDate(Date paymentDate) {
        this.paymentDate = paymentDate;
    }




}


